spring:
  datasource:
    url: jdbc:mysql://fisolution-database.cqhk6r7fujpk.ap-northeast-2.rds.amazonaws.com:3306/UNIFIED_TEST
    username: fismain
    password: 4jLKvkSYkalAvoQ
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

logging:
  level:
    root: INFO
  profiles: local


webhook-uri: https://hooks.slack.com/services/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
log-dir: './logs'