name: Add issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.5.0
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/FISOLUTION/projects/16
          # A GitHub personal access token with write access to the project
          github-token: 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
          # A comma-separated list of labels to use as a filter for issue to be added
          labeled: # optional
          # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
          label-operator: # optional
